LogIn with Email/Password and Google
BrightCoders-Institute/reto-reservacion-de-vuelos-team2 pull request #25
Opened 2023-07-11 21:11 UTC by AlbertoG22

# Description

What did you implemented/Why did you implemented this:
- Creation and implementation of custom hooks for the form fields, validation of email and password and show/hide password.
- Implementation of the logic to "log in" with the email and google methods.
- Added logic to change the error message as appropriate. Some errors handled are:
  - In sign up if there is already an account created.
  - If the domain in the email is missing.
  - In the login if the email doesn't have an account created.
  - If the password is wrong.
- Creation and implementation of Loader component, when the action is successful it shows a message, if it doesn't shows an error.
- The loader is implemented for both sign up and log in screens, with email and Google authentication methods.

## Screenshots
<img src="https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team2/assets/47892591/6676ca3b-cde4-430e-8fd4-f3efd31f78d4" alt="Texto alternativo" width="300" height="700">
<img src="https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team2/assets/47892591/189ac93e-fc31-42b2-96c9-0564c7b1ab81" alt="Texto alternativo" width="300" height="700">
<img src="https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team2/assets/47892591/0696abab-be35-47c3-85f1-9d341604afee" alt="Texto alternativo" width="300" height="700">
<img src="https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team2/assets/47892591/95bcee0d-68ad-48a7-833b-fceb4fa9ddd8" alt="Texto alternativo" width="300" height="700">
<img src="https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team2/assets/47892591/a166e545-dc5f-433c-8992-ccc8ddb58299" alt="Texto alternativo" width="300" height="700">
<img src="https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team2/assets/47892591/8474a8a5-7544-4b95-b2dc-16741ab38a03" alt="Texto alternativo" width="300" height="700">
<img src="https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team2/assets/47892591/e49f0054-0b5f-4930-a177-efbab9290983" alt="Texto alternativo" width="300" height="700">
<img src="https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team2/assets/47892591/c17c2172-bfb1-4fce-8d55-d84b31c7bb8d" alt="Texto alternativo" width="300" height="700">
<img src="https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team2/assets/47892591/c01eef43-2a8f-4d92-a3a9-aca1ad4d925a" alt="Texto alternativo" width="300" height="700">

![image](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team2/assets/47892591/b316c942-5b84-499c-a970-de3cd62ebc63)

2023-07-11 21:31 UTC, Lizzflores approved these changes

2023-07-11 23:36 UTC, landillo approved these changes
nice job team!

2023-07-11 23:46 UTC, wiltrouble requested changes, later dismissed

2023-07-11 23:46 UTC, wiltrouble commented on src/styles/AppStyles.js
> +    // backgroundColor: '#343434',
Remove this comment

2023-07-11 23:46 UTC, wiltrouble commented on src/styles/AppStyles.js
> +    // backgroundColor: '#393E51',
Remove this comment

2023-07-11 23:46 UTC, wiltrouble commented on src/styles/AppStyles.js
> +    // flex: 1,
Remove this comment

2023-07-12 00:22 UTC, FranciscoSenestrari approved these changes

2023-07-12 00:25 UTC, merged